Web/RavenAge.Web/Controllers/ArenaController.cs
namespace RavenAge.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using Newtonsoft.Json;
    using RavenAge.Services.Data.ArenaBattleService;
    using RavenAge.Services.Data.ArenaService;
    using RavenAge.Web.ViewModels.Arena;

    public class ArenaController : Controller
    {
        private readonly IArenaService arenaService;
        private readonly IArenaBattleService arenaBattleService;

        public ArenaController(IArenaService arenaService, IArenaBattleService arenaBattleService)
        {
            this.arenaService = arenaService;
            this.arenaBattleService = arenaBattleService;
        }

        public IActionResult Index()
        {
            var userId = this.GetUserId();
            var model = this.arenaService.GetArenaList(userId);
            return this.View(model);
        }

        public async Task<IActionResult> Attack(int id)
        {
            var attackerId = this.GetUserId();
            var defenderId = id;

            var viewModel = this.arenaService.GetArenaList(attackerId);

            viewModel.BattleResult = await this.arenaBattleService.Attack(attackerId, defenderId);

            return this.View("Index", viewModel);
        }

        internal string GetUserId()
        {
            return this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
    }
}

Web/RavenAge.Web/Controllers/CityController.cs
namespace RavenAge.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using RavenAge.Services.CityService.Data;
    using RavenAge.Services.Data.BarracksService;
    using RavenAge.Web.ViewModels.Barracks;

    public class CityController : Controller
    {
        private readonly ICityService cityService;
        private readonly IBarracksService barrackService;

        public CityController(ICityService cityService, IBarracksService barrackService)
        {
            this.cityService = cityService;
            this.barrackService = barrackService;
        }

        public IActionResult Index()
        {
           var model = this.cityService.GetCity(this.GetUserId());

           return this.View(model);
        }

        //[HttpPost]
        //public async Task<IActionResult> Index(HireSoldiersInputModel input)
        //{
        //    var userId = this.GetUserId();

        //    if (!this.ModelState.IsValid)
        //    {
        //        return this.View();
        //    }

        //    await this.barrackService.AddSoldiersAsync(input, userId);

        //    var model = this.cityService.GetCity(userId);

        //    return this.View(model);
        //}

        public IActionResult BarracksStats()
        {
            var model = this.cityService.GetBarracks(this.GetUserId());
            return this.View(model);
        }

        public IActionResult TownhallStats()
        {
            var model = this.cityService.GetTownHall(this.GetUserId());
            return this.View(model);
        }


        internal string GetUserId()
        {
            return this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
    }
}

Web/RavenAge.Web/Controllers/EventController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace RavenAge.Web.Controllers
{
    public class EventController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Web/RavenAge.Web/Controllers/WorldController.cs
namespace RavenAge.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    public class WorldController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }
    }
}

Web/RavenAge.Web/Views/World/Index.cshtml
@{
    this.ViewData["Title"] = "Raven World";
}

<head>
    <link rel="stylesheet" href="~/css/world.css" asp-append-version="true" />
</head>

<div id="worldMap">

    <img class="img-fluid justify-content-center" src="~/images/World/Raven-event-3.jpg" style="width: 1920px; height: auto; z-index: 100;" />

    <a id="anchor-level1" class="text-dark" asp-controller="City" asp-action="Index" asp-route-enemyName="">
        <p class="font-weight-bold p-0">City View - 1</p>
    </a>

    <a id="anchor-level2" class="text-dark">
        <p class="font-weight-bold p-0">Avatar - 2</p>
    </a>

    <a id="anchor-level3" class="text-dark" asp-controller="Arena" asp-action="Index" asp-route-enemyName="">
        <h1 class="font-weight-bold row justify-content-center">Arena</h1>
    </a>

    <a id="anchor-level4" class="text-dark" asp-controller="Event" asp-action="Index" asp-route-enemyName="">
        <h1 class="font-weight-bold row justify-content-center">Event</h1>
    </a>

    <a id="anchor-level5" class="text-dark">
        <h1 class="font-weight-bold row justify-content-center">Guild battle</h1>
    </a>

</div>