Web/RavenAge.Web/Controllers/CityController.cs
namespace RavenAge.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using RavenAge.Services.CityService.Data;
    using RavenAge.Services.Data.BarracksService;
    using RavenAge.Web.ViewModels.Barracks;

    public class CityController : Controller
    {
        private readonly ICityService cityService;
        private readonly IBarracksService barrackService;

        public CityController(ICityService cityService, IBarracksService barrackService)
        {
            this.cityService = cityService;
            this.barrackService = barrackService;
        }

        public IActionResult Index()
        {
           var model = this.cityService.GetCity(this.GetUserId());

           return this.View(model);
        }

        //[HttpPost]
        //public async Task<IActionResult> Index(HireSoldiersInputModel input)
        //{
        //    var userId = this.GetUserId();

        //    if (!this.ModelState.IsValid)
        //    {
        //        return this.View();
        //    }

        //    await this.barrackService.AddSoldiersAsync(input, userId);

        //    var model = this.cityService.GetCity(userId);

        //    return this.View(model);
        //}

        public IActionResult BarracksStats()
        {
            var model = this.cityService.GetBarracks(this.GetUserId());
            return this.View(model);
        }

        public IActionResult TownhallStats()
        {
            var model = this.cityService.GetTownHall(this.GetUserId());
            return this.View(model);
        }


        internal string GetUserId()
        {
            return this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
    }
}

Web/RavenAge.Web/Controllers/GuildController.cs
namespace RavenAge.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using RavenAge.Services.Data.GuildService;
    using RavenAge.Web.ViewModels.Guild;
    using System.Security.Claims;
    using System.Threading.Tasks;

    public class GuildController : Controller
    {
        private readonly IGuildService guildService;

        public GuildController(IGuildService guildService)
        {
            this.guildService = guildService;
        }

        public IActionResult Index()
        {
            var model = new GuildListViewModel();
            model.Guilds = this.guildService.GetGuilds();

            return this.View(model);
        }

        public IActionResult Join()
        {
            return this.RedirectToAction("Index");
        }

        public IActionResult Leave()
        {
            return this.RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateGuildInputViewModel model)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.guildService.Create(userId, model.Name);
            return this.RedirectToAction("Index");
        }
    }
}

Web/RavenAge.Web/Views/Shared/_BarracksModal.cshtml
@model RavenAge.Web.ViewModels.City.CityViewModel;


<div class="row justify-content-between">

    <div class="col-md-3">
        <p id ="Archers" class="text-center">Archers @Model.Archers</p>
        <img class="img-fluid justify-content-center" src="~/images/Soldiers/HumanArchar.jpg" />
    </div>

    <div class="col-md-3">
        <p id="Infantry" class=" text-center">Infantry @Model.Infantry</p>
        <img class="img-fluid justify-content-center" src="~/images/Soldiers/HumanInfantry.jpg" />
    </div>

    <div class="col-md-3">
        <p id="Cavalry" class=" text-center">Cavalry @Model.Cavalry</p>
        <img class="img-fluid justify-content-center" src="~/images/Soldiers/HumanCavalery.jpg" />
    </div>

    <div class="col-md-3">
        <p id="Artillery" class="artillery text-center">Artillery @Model.Artillery</p>
        <img class="img-fluid justify-content-center" src="~/images/Soldiers/HumanTrebuchet.jpg" />
    </div>

</div>

<div class="row justify-content-between ml-2">

    <div class="col-md-3">
        <div asp-validation-summary="ModelOnly" class="text-danger col-md-12"></div>
            <div class="col-md-10">
                <label asp-for="@Model.HireSoldiersInputModel.ArcherQuantity"></label>
                <input name="archerquantity" asp-for="@Model.HireSoldiersInputModel.ArcherQuantity" value="0" class="form-control" />
                <span asp-validation-for="@Model.HireSoldiersInputModel.ArcherQuantity" class="text-danger"></span>
            </div>
            <input type="submit" value="Hire" class="btn btn-primary mt-2 ml-3" style="width: 6.7rem;" />

    </div>

    <div class="col-md-3">
        <div asp-validation-summary="ModelOnly" class="text-danger col-md-12"></div>

            <div class="col-md-10">
                <label asp-for="@Model.HireSoldiersInputModel.InfantryQuantity"></label>
                <input name="infantryquantity" asp-for="@Model.HireSoldiersInputModel.InfantryQuantity" value="0" class="form-control" />
                <span asp-validation-for="@Model.HireSoldiersInputModel.InfantryQuantity" class="text-danger"></span>
            </div>

            <input type="submit" value="Hire" class="btn btn-primary mt-2 ml-3" style="width: 6.7rem;" />

    </div>

    <div class="col-md-3">
        <div asp-validation-summary="ModelOnly" class="text-danger col-md-12"></div>

            <div class="col-md-10">
                <label asp-for="@Model.HireSoldiersInputModel.CavalryQuantity"></label>
                <input name="cavalryquantity" asp-for="@Model.HireSoldiersInputModel.CavalryQuantity" value="0" class="form-control" />
                <span asp-validation-for="@Model.HireSoldiersInputModel.CavalryQuantity" class="text-danger"></span>
            </div>

            <input type="submit" value="Hire" class="btn btn-primary mt-2 ml-3" style="width: 6.7rem;" />
 
    </div>

    <div class="col-md-3">
        <div asp-validation-summary="ModelOnly" class="text-danger col-md-12"></div>

            <div class="col-md-10">
                <label asp-for="@Model.HireSoldiersInputModel.ArtilleryQuantity"></label>
                <input name="artilleryquantity" asp-for="@Model.HireSoldiersInputModel.ArtilleryQuantity" value="0" class="form-control" />
                <span asp-validation-for="@Model.HireSoldiersInputModel.ArtilleryQuantity" class="text-danger"></span>
            </div>
            <input type="submit" value="Hire" class="btn btn-primary mt-2 ml-3" style="width: 6.7rem;" />
    </div>

</div>

<input id="cityId" type="hidden" asp-for="@Model.HireSoldiersInputModel.CityId" value="@Model.Id"/>

<div class="row justify-content-between col-md-12">

    <div class="col-md-3">
        <p class="text-center">50 Silver</p>
        <p class="text-center">50 Wood</p>
    </div>

    <div class="col-md-3">
        <p class="text-center">100 Silver</p>
        <p class="text-center">15 Wood</p>
    </div>

    <div class="col-md-3">
        <p class="text-center">100 Silver</p>
        <p class="text-center">15 Wood</p>
    </div>

    <div class="col-md-3">
        <p class="text-center">25 Silver</p>
        <p class="text-center">100 Wood</p>
    </div>

</div>

Web/RavenAge.Web/Views/Shared/_CreateGuild.cshtml
@model RavenAge.Web.ViewModels.Guild.CreateGuildInputViewModel;

<div class="row justify-content-between ml-2">
    <div class="col-md-10">
        <form method="post" enctype="multipart/form-data">
        <div asp-validation-summary="ModelOnly" class="text-danger col-md-12"></div>
        <div class="col-md-10">
            <label asp-for="@Model.Name">Guild name*:</label>
            <input name="name" asp-for="@Model.Name" value="My guild name" class="form-control col-md-12" />
            <span asp-validation-for="@Model.Name" class="text-danger"></span>
        </div>
        <input type="submit" asp-controller="Guild" asp-action="Create" value="Create" class="btn btn-primary mt-2 ml-3" style="width: 6.7rem;" />
        </form>

    </div>
</div>

Web/RavenAge.Web/Views/Shared/_DefenceWallModal.cshtml
@model RavenAge.Web.ViewModels.City.CityViewModel;


<div>

    <div>
        <p id="DefencePoints">Curent points: @Model.DefenceWall.Defence</p>
    </div>

    <div>

        <p>Raise the level of the Wall to increase the city defence </p>

        <div class="row ml-1">
            <a id="DefenceWallUpgrade" class="button-primary text-success mr-3 btn btn-outline-success" >Level Up</a>

            <p>
                <span>Price:</span>
                <span id="DefenceWallSilverUpgradeCost" class="text-warning">Silver: @Model.DefenceWall.SilverPrice</span>,
                <span id="DefenceWallStoneUpgradeCost" class="text-secondary">Stone: @Model.DefenceWall.StonePrice</span>,
                <span id="DefenceWallWoodUpgradeCost"class="text-danger">Wood: @Model.DefenceWall.WoodPrice</span>
            </p>
        </div>


    </div>

</div>

Web/RavenAge.Web/Views/Shared/_FarmModal.cshtml
@model RavenAge.Web.ViewModels.City.CityViewModel;


<div>

    <div>
        <p id="CurrentFarmProduction">Current Production: @Model.Farm.FoodProduction</=p>

        <p id="NextLevelFarmProduction">Next Level Production: @(Model.Farm.FoodProduction + 200)</p>
    </div>

    <div>

        <p>Raise the level of the farm to increase the food production </p>

        <div class="row ml-1">
            <a id="FarmLevel" class="button-primary text-success mr-3 btn btn-outline-success">Level Up</a>

            <p>
                <span>Price:</span>
                <span id="FarmSilverCost" class="text-warning">Silver: @Model.Farm.SilverPrice</span>,
                <span id="FarmStoneCost" class="text-secondary">Stone: @Model.Farm.StonePrice</span>,
                <span id="FarmWoodCost" class="text-danger">Wood: @Model.Farm.WoodPrice</span>
            </p>
        </div>


    </div>

</div>

Web/RavenAge.Web/Views/Shared/_HouseModal.cshtml
@model RavenAge.Web.ViewModels.City.CityViewModel;


<div>

    <div>
        <p id="HouseCurrentWorkers">Curent workers: @Model.Workers</p>
        <p id="HouseIncomePerWorker">Income per Worker: 4</p>
        <p id="HouseTotalIncome">Silver income: @(Model.Workers * 4)</p>
        <p id="WorkerLimit">Workers limit: @Model.House.WorkerLimit</p>
    </div>

    <div>

        <p>Raise the level of the houses to increase the workers' limit </p>

        <div class="row ml-1">
            <a id="UpgradeHouse" class="button-primary text-success mr-3 btn btn-outline-success">Level Up</a>

            <p>
                <span>Price:</span>
                <span id="HouseSilverUpgradeCost" class="text-warning">Silver: @Model.House.SilverPrice</span>,
                <span id="HouseStoneUpgradeCost" class="text-secondary">Stone: @Model.House.StonePrice</span>,
                <span id="HouseWoodUpgradeCost"class="text-danger">Wood: @Model.House.WoodPrice</span>
            </p>
        </div>


    </div>

</div>

Web/RavenAge.Web/Views/Shared/_Layout.cshtml
@using RavenAge.Common
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8-sig" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@this.ViewData["Title"] - @GlobalConstants.SystemName</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/sidebar.css" asp-append-version="true" />
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <script src="https://kit.fontawesome.com/f909b4a59b.js" crossorigin="anonymous"></script>
    @RenderSection("CssFile", required: false)
</head>

<body>

    <header>

        <nav class="navbar navbar-expand-sm navbar-light bg-transparent fixed-top p-0">

            <div id="layoutLogo" class="container-fluid m-0 p-0">

                <div id="left" class="row col-md-4">
                    <a id="firstLink" class="nav-link text-light" asp-area="" asp-controller="City" asp-action="Index">My city</a>

                    <a class="nav-link text-light" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>

                <div id="right" class="col-md-4">

                    <div class="ml-5">
                        <partial name="_LoginPartial" />
                    </div>

                </div>

            </div>
        </nav>
    </header>

    <main role="main">

        <partial name="_CookieConsentPartial" />

        @this.RenderBody()
    </main>

    <script type="module" src="~/lib/jquery/dist/jquery.min.js" asp-append-version="true"></script>
    <script type="module" src="~/lib/jquery-validation/dist/jquery.validate.min.js" asp-append-version="true"></script>
    <script type="module" src="~/lib/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js" asp-append-version="true"></script>
    <script type="module" src="~/lib/bootstrap/dist/js/bootstrap.min.js" asp-append-version="true"></script>
    <script type="module" src="~/js/site.min.js" asp-append-version="true"></script>

    @await this.RenderSectionAsync("Scripts", required: false)
</body>
</html>

Web/RavenAge.Web/Views/Shared/_SawMillModal.cshtml
@model RavenAge.Web.ViewModels.City.CityViewModel;


<div>

    <div>
        <p id="SawMillCurrentProduction">Current Production: @Model.WoodMine.Production</p>

        <p id="SawMillNextLevelProduction">Next Level Production: @(Model.WoodMine.Production + 200)</p>
    </div>

    <div>

        <p>Raise the level of the saw mill to increase the wood production </p>

        <div class="row ml-1">
            <a id="SawMillUpgrade" class="button-primary text-success mr-3 btn btn-outline-success">Level Up</a>

            <p>
                <span>Price:</span>
                <span id="SawMillSilverUpgradeCost" class="text-warning">Silver: @Model.WoodMine.SilverPrice</span>,
                <span id="SawMillStoneUpgradeCost" class="text-secondary">Stone: @Model.WoodMine.StonePrice</span>,
                <span id="SawMillWoodUpgradeCost" class="text-danger">Wood: @Model.WoodMine.WoodPrice</span>
            </p>
        </div>


    </div>

</div>

Web/RavenAge.Web/Views/Shared/_StoneMineModal.cshtml
@model RavenAge.Web.ViewModels.City.CityViewModel;


<div>

    <div>
        <p id="StoneMineCurrentProduction" >Current Production: @Model.StoneMine.Production</p>

        <p id="StoneMineNextLevelProduction">Next Level Production: @(Model.StoneMine.Production + 200)</p>
    </div>

    <div>

        <p>Raise the level of the stone mine to increase the stone production </p>

        <div class="row ml-1">
            <a id="StoneMineUpgrade" class="button-primary text-success mr-3 btn btn-outline-success">Level Up</a>

            <p>
                <span>Price:</span>
                <span id="StoneMineSilverUpgradeCost" class="text-warning">Silver: @Model.WoodMine.SilverPrice</span>,
                <span id="StoneMineStoneUpgradeCost" class="text-secondary">Stone: @Model.WoodMine.StonePrice</span>,
                <span id="StoneMineWoodUpgradeCost" class="text-danger">Wood: @Model.WoodMine.WoodPrice</span>
            </p>
        </div>


    </div>

</div>

Web/RavenAge.Web/Views/Shared/_TownHallModal.cshtml
@model RavenAge.Web.ViewModels.City.CityViewModel;


<div>

    <div>
      <p id="ArmyLimit">Army limit: @Model.TownHall.ArmyLimit</p>
    </div>

    <div>

        <p>Raise the level of the townhall to increase the army limit and to reach higher buildings levels</p>

        <div class="row ml-1">
            <a id="TownHallUpgrade" class="button-primary text-success mr-3 btn btn-outline-success">Level Up</a>

            <p>
                <span>Price:</span>
                <span id="TownHallSilverCost" class="text-warning">Silver: @Model.TownHall.SilverPrice</span>,
                <span id="TownHallStoneCost" class="text-secondary">Stone: @Model.TownHall.StonePrice</span>,
                <span id="TownHallWoodCost" class="text-danger">Wood: @Model.TownHall.WoodPrice</span>
            </p>
        </div>


    </div>

</div>