Web/RavenAge.Web/Controllers/CityController.cs
namespace RavenAge.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Security.Claims;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;
    using RavenAge.Services.CityService.Data;
    using RavenAge.Services.Data.BarracksService;
    using RavenAge.Web.ViewModels.Barracks;

    public class CityController : Controller
    {
        private readonly ICityService cityService;
        private readonly IBarracksService barrackService;

        public CityController(ICityService cityService, IBarracksService barrackService)
        {
            this.cityService = cityService;
            this.barrackService = barrackService;
        }

        public IActionResult Index()
        {
           var model = this.cityService.GetCity(this.GetUserId());

           return this.View(model);
        }

        //[HttpPost]
        //public async Task<IActionResult> Index(HireSoldiersInputModel input)
        //{
        //    var userId = this.GetUserId();

        //    if (!this.ModelState.IsValid)
        //    {
        //        return this.View();
        //    }

        //    await this.barrackService.AddSoldiersAsync(input, userId);

        //    var model = this.cityService.GetCity(userId);

        //    return this.View(model);
        //}

        public IActionResult BarracksStats()
        {
            var model = this.cityService.GetBarracks(this.GetUserId());
            return this.View(model);
        }

        public IActionResult TownhallStats()
        {
            var model = this.cityService.GetTownHall(this.GetUserId());
            return this.View(model);
        }


        internal string GetUserId()
        {
            return this.User.FindFirst(ClaimTypes.NameIdentifier).Value;
        }
    }
}

Web/RavenAge.Web/Controllers/GuildController.cs
namespace RavenAge.Web.Controllers
{
    using Microsoft.AspNetCore.Mvc;
    using RavenAge.Services.Data.GuildService;
    using RavenAge.Web.ViewModels.Guild;
    using System.Security.Claims;
    using System.Threading.Tasks;

    public class GuildController : Controller
    {
        private readonly IGuildService guildService;

        public GuildController(IGuildService guildService)
        {
            this.guildService = guildService;
        }

        public IActionResult Index()
        {
            var model = new GuildListViewModel();
            model.Guilds = this.guildService.GetGuilds();

            return this.View(model);
        }

        public IActionResult Join()
        {
            return this.RedirectToAction("Index");
        }

        public IActionResult Leave()
        {
            return this.RedirectToAction("Index");
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateGuildInputViewModel model)
        {
            var userId = this.User.FindFirst(ClaimTypes.NameIdentifier).Value;

            await this.guildService.Create(userId, model.Name);
            return this.RedirectToAction("Index");
        }
    }
}

Web/RavenAge.Web/Controllers/WorldController.cs
namespace RavenAge.Web.Controllers
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Threading.Tasks;

    using Microsoft.AspNetCore.Mvc;

    public class WorldController : Controller
    {
        public IActionResult Index()
        {
            return this.View();
        }
    }
}

Web/RavenAge.Web/Views/City/BarracksStats.cshtml
@model RavenAge.Web.ViewModels.City.BarracksViewModel;
---Barracks Modal---
<div>Description: @Model.Description</div>
<div>Price: @Model.Price</div>
<div>Level: @Model.Level</div>
<div>Training Limit: @Model.TrainingLimit</div>

Web/RavenAge.Web/Views/City/Index.cshtml
@model RavenAge.Web.ViewModels.City.CityViewModel
@{
    this.ViewData["Title"] = "Raven City";
}

<head>
    <link rel="stylesheet" href="~/css/city.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/css/modal.css" asp-append-version="true" />
</head>

<div id="wrapper">

    <img class="img-fluid justify-content-center" src="~/images/City/Raven-village-3.jpeg" style="width: 1920px; height: auto;" />

    <a id="anchor-level1" class="playsound" href="~/Sounds/Marching_Barracks.mp3" data-toggle="modal" data-target="#modalBarracksCenter">
        <p class="font-weight-bold p-0">Barracks</p>
        <p>Lvl: @Model.Barracks.Level</p>
    </a>

    <a id="anchor-level2" class="playsound" href="~/Sounds/Townhall_sound.mp3" data-toggle="modal" data-target="#modalTownhallCenter">
        <p class="font-weight-bold p-0">Townhall</p>
        <p>Lvl: @Model.TownHall.Level</p>
    </a>

    <a id="anchor-level3" data-toggle="modal" data-target="#modalHouseCenter">
        <p class="font-weight-bold p-0">House</p>
        <p>Lvl: @Model.House.Level</p>
    </a>

    <a id="anchor-level4" class="playsound" href="~/Sounds/Farm_Sound.mp3" data-toggle="modal" data-target="#modalFarmCenter">
        <p class="font-weight-bold p-0">Farm</p>
        <p>Lvl: @Model.Farm.Level</p>
    </a>

    <a id="anchor-level5" class="playsound" href="~/Sounds/SawMill_Sound.mp3" data-toggle="modal" data-target="#modalSawMillCenter">
        <p class="font-weight-bold p-0">Saw mill</p>
        <p>Lvl: @Model.WoodMine.Level</p>
    </a>

    <a id="anchor-level6" class="playsound" href="~/Sounds/StoneQuarry_Sound.mp3" data-toggle="modal" data-target="#modalStoneMineCenter">
        <p class="font-weight-bold p-0">Stone quarry</p>
        <p>Lvl: @Model.StoneMine.Level</p>
    </a>

    <a id="anchor-level7" href="~/Sounds/Marketplace_Sound.mp3" class="playsound text-dark">
        <p class="font-weight-bold p-0">Marketplace - 7</p>
    </a>

    <a id="anchor-level8" class="playsound " text-dark"" href="~/Sounds/DefenceWallGate_Sound.mp3" data-toggle="modal" data-target="#modalDefenceWallCenter">
        <p class="font-weighсt-bold p-0">Stone wall - 8</p>
        <p>Lvl: @Model.DefenceWall.Level</p>
    </a>

    <a id="anchor-level9" class="-dark" asp-controller="World" asp-action="Index" asp-route-enemyName="">
        <p class="font-weight-bold p-0">World View - 9</p>
    </a>

    <a id="anchor-level10" class="row justify-content-around">

        <div class="">
            <span class="currency-image-container">Silver - <i style="color:silver" class=" fas fa-coins"></i></span>
            @if (Model.Silver > 999999)
            {
                <span class="resource">@(Math.Round((Model.Silver / 1000000), 3)) M</span>
            }
            else if (Model.Silver > 999)
            {
                <span class="resource">@(Math.Round((Model.Silver / 1000), 2)) k</span>
            }
            else
            {
                <span class="resource">@(Math.Floor(Model.Silver))</span>
            }
        </div>


        <div class="">
            <span class="currency-image-container">Stone - <i style="color:black" class="fas fa-mountain"></i></span>
            @if (Model.Stone > 999999)
            {
                <span class="resource">@(Math.Round((Model.Stone / 1000000), 3)) M</span>
            }
            else if (Model.Stone > 999)
            {
                <span class="resource">@(Math.Round((Model.Stone / 1000), 2)) k</span>
            }
            else
            {
                <span class="resource">@(Math.Floor(Model.Stone))</span>
            }
        </div>

        <div class="">
            <span class="currency-image-container" >Wood - <i style="color:forestgreen" class="fas fa-tree"></i></span>
            @if (Model.Wood > 999999)
            {
                <span class="resource">@(Math.Round((Model.Wood / 1000000), 3)) M</span>
            }
            else if (Model.Wood > 999)
            {
                <span class="resource">@(Math.Round((Model.Wood / 1000), 2)) k</span>
            }
            else
            {
                <span class="resource">@(Math.Floor(Model.Wood))</span>
            }
        </div>
    </a>

    @*Avatar*@
    <a id="anchor-level11" class="text-dark">
        <p class="font-weight-bold p-0">
            <img src="~/images/Avatars/@(Model.Avatar +".png")" style="max-width: 100%; height: auto;" alt="Alternate Text" />
        </p>
    </a>

    <a id="anchor-level12" class="playsound" asp-controller="Guild" asp-action="Index">
        <p class="font-weight-bold p-0">Guild</p>
    </a>

</div>
<audio id="playTarget" src="" autoplay style="display:none"></audio>

<!-- Barracks Modal -->

<div class="modal fade" id="modalBarracksCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalCenterTitle">
                    Barracks

                    <span class="resource text-warning">Silver - @(Math.Floor(Model.Silver))</span>
                    <span class="resource text-secondary">Stone - @(Math.Floor(Model.Stone))</span>
                    <span class="resource text-danger">Wood - @(Math.Floor(Model.Wood))</span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <partial name="_BarracksModal" />

            </div>
            <div class="modal-footer">
                <p>@Model.Barracks.Description</p>
            </div>
        </div>
    </div>
</div>

<!-- House Modal -->

<div class="modal fade" id="modalHouseCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalCenterTitle">
                    House

                    <span class="resource text-warning">Silver - @(Math.Floor(Model.Silver))</span>
                    <span class="resource text-secondary">Stone - @(Math.Floor(Model.Stone))</span>
                    <span class="resource text-danger">Wood - @(Math.Floor(Model.Wood))</span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <partial name="_HouseModal" />

            </div>
            <div class="modal-footer">
                <p>@Model.House.Description</p>
            </div>
        </div>
    </div>
</div>
<form method="post" id="antiForgeryForm">
</form>

<!-- Farm Modal -->

<div class="modal fade" id="modalFarmCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalCenterTitle">
                    Farm
                    <span class="resource text-warning">Silver - @(Math.Floor(Model.Silver))</span>
                    <span class="resource text-primary">Stone - @(Math.Floor(Model.Stone))</span>
                    <span class="resource text-danger">Wood - @(Math.Floor(Model.Wood))</span>

                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <partial name="_FarmModal" />

            </div>
            <div class="modal-footer">
                <p>@Model.Farm.Description</p>
            </div>
        </div>
    </div>
</div>

<!-- Saw mill Modal -->

<div class="modal fade" id="modalSawMillCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalCenterTitle">
                    Saw mill
                    <span class="resource text-warning">Silver - @(Math.Floor(Model.Silver))</span>
                    <span class="resource text-secondary">Stone - @(Math.Floor(Model.Stone))</span>
                    <span class="resource text-danger">Wood - @(Math.Floor(Model.Wood))</span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <partial name="_SawMillModal" />

            </div>
            <div class="modal-footer">
                <p>@Model.WoodMine.Description</p>
            </div>
        </div>
    </div>
</div>

<!-- Stone mine Modal -->

<div class="modal fade" id="modalStoneMineCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalCenterTitle">
                    Stone Mine
                    <span class="resource text-warning">Silver - @(Math.Floor(Model.Silver))</span>
                    <span class="resource resource text-secondary">Silver - @(Math.Floor(Model.Stone))</span>
                    <span class="resource text-danger">Wood - @(Math.Floor(Model.Wood))</span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <partial name="_StoneMineModal" />

            </div>
            <div class="modal-footer">
                <p>@Model.StoneMine.Description</p>
            </div>
        </div>
    </div>
</div>

<!-- TownHall Modal -->

<div class="modal fade" id="modalTownhallCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalCenterTitle">
                    TownHall

                    <span class="resource text-warning">Silver - @(Math.Floor(Model.Silver))</span>
                    <span class="resource text-secondary">Stone - @(Math.Floor(Model.Stone))</span>
                    <span class="resource text-danger">Wood - @(Math.Floor(Model.Wood))</span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <partial name="_TownHallModal" />

            </div>
            <div class="modal-footer">
                <p>@Model.TownHall.Description</p>
            </div>
        </div>
    </div>
</div>


<!-- DefenceWall Modal -->

<div class="modal fade" id="modalDefenceWallCenter" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered modal-lg" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalCenterTitle">
                    Defence Wall

                    <span class="resource text-warning">Silver - @(Math.Floor(Model.Silver))</span>
                    <span class="resource text-secondary">Stone - @(Math.Floor(Model.Stone))</span>
                    <span class="resource text-danger">Wood - @(Math.Floor(Model.Wood))</span>
                </h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">

                <partial name="_DefenceWallModal" />

            </div>
            <div class="modal-footer">
                <p>@Model.DefenceWall.Description</p>
            </div>
        </div>
    </div>
</div>

@section Scripts{
    <script type="module" src="~/Scripts/HireUnits.js"></script>
    <script type="module" src="~/Scripts/FarmUpgrade.js"></script>
    <script type="module" src="~/Scripts/TownHallUpgrade.js"></script>
    <script type="module" src="~/Scripts/BuildingsSounds.js"></script>
    <script type="module" src="~/Scripts/SawMillUpgrade.js"></script>
    <script type="module" src="~/Scripts/StoneMine.js"></script>
    <script type="module" src="~/Scripts/HouseUpgrade.js"></script>
    <script type="module" src="~/Scripts/DefenceWallUpgrade.js"></script>
    <script type="module" src="~/Scripts/UpdateResource.js"></script>
}

Web/RavenAge.Web/Views/City/TownhallStats.cshtml
@model RavenAge.Web.ViewModels.City.TownHallViewModel;

---Townhall modal---
<div>@Model.Description</div>
<div>@Model.Price</div>
<div>@Model.Level</div>
<div>@Model.ArmyLimit</div>